/*! \file Dependent.java
    \date 10/14/2020
    \author Raymond Moorhead
    \brief Contains Dependent class
*/

package com.xerus.records.entity;

import java.util.Date;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.stereotype.Component;

import com.fasterxml.jackson.annotation.JsonFormat;

@Document(collection="dependent")
//! Container for Dependent information, to be used by Enrollee
public class Dependent {
	@Id
	//! The unique id of the Dependent, generated by the Mongo server
	private String id;
	//! The Full Name of the Enrollee
	private String name;
	
	@JsonFormat(pattern="MM-dd-yyyy")
	//! The birth date of the Dependent, saved in 'MM-dd-yyyy' format
	private Date birthDate;
	
	// CONSTRUCTORS
	
	//! Default Dependent constructor, performs no significant operations
	public Dependent() {
		super();
	}
	
	/*!
		\brief Constructor which enables initialization of name and birthDate
		\param name The value to assign to Dependent.name
		\param birthDate The value to assign to Dependent.birthDate
	 */
	public Dependent(String name, Date birthDate) {
		super();
		this.name = name;
		this.birthDate = birthDate;
	}
	
	// GETTERS AND SETTERS

	/*!
		\brief Getter for Dependent.id, performs no unexpected operations
		\return Dependent.id
	 */
	public String getId() {
		return id;
	}
	
	/*!
		\brief Setter for Dependent.id, performs no unexpected operations
		\param id The id to set Dependent.id with
	 */
	public void setId(String id) {
		this.id = id;
	}
	
	/*!
		\brief Getter for Dependent.name, performs no unexpected operations
		\return Dependent.name
	 */
	public String getName() {
		return name;
	}
	
	/*!
		\brief Setter for Dependent.name, performs no unexpected operations
		\param name The name to set Dependent.name with
	 */
	public void setName(String name) {
		this.name = name;
	}
	
	/*!
		\brief Getter for Dependent.birthDate, performs no unexpected operations
		\return Dependent.birthDate
	 */
	public Date getBirthDate() {
		return birthDate;
	}
	
	/*!
		\brief Setter for Dependent.birthDate, performs no unexpected operations
		\param birthDate The birth date to set Dependent.birthDate with
	 */
	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}
}
