/*! \file Dependent.java
    \date 10/14/2020
    \author Raymond Moorhead
    \brief Contains Dependent class
*/

package com.xerus.records.entity;

import java.util.Date;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.stereotype.Component;

import com.fasterxml.jackson.annotation.JsonFormat;

@Document(collection="dependent")
//! Container for Dependent information, to be used by Enrollee
public class Dependent {
	@Id
	//! The unique id of the Dependent, generated by the Mongo server
	private String id;
	//! The Full Name of the Enrollee
	private String name;
	
	@JsonFormat(pattern="MM-dd-yyyy")
	//! The birth date of the Dependent, in 'MM-dd-yyyy' format
	private Date birthDate;
	
	// CONSTRUCTORS
	
	public Dependent() {
		super();
	}
	
	public Dependent(String name, Date birthDate) {
		super();
		this.name = name;
		this.birthDate = birthDate;
	}
	
	// GETTERS AND SETTERS

	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public Date getBirthDate() {
		return birthDate;
	}
	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}
}
