/*! \file Enrollee.java
    \date 10/14/2020
    \author Raymond Moorhead
    \brief Contains Enrollee class
*/

package com.xerus.records.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.stereotype.Component;

import com.fasterxml.jackson.annotation.JsonFormat;

@Document(collection="enrollee")
//! Container for Enrollee information, such as id, name, etc.
public class Enrollee {

	@Id
	//! The unique id of the Enrollee, generated by the Mongo server
	private String id;
	//! The Full Name of the Enrollee
	private String name;
	//! The activation status of the Enrollee's application
	private boolean activationStatus;
	
	@JsonFormat(pattern="MM-dd-yyyy")
	//! The birth date of the Enrollee, in 'MM-dd-yyyy' format
	private Date birthDate;
	
	//! The phone number of the Enrollee, is optional
	private String phoneNumber;
	
	@DBRef
	//! The dependents of the Enrollee, are optional
	private Set<Dependent> dependents;
	
	// CONSTRUCTORS
	
	public Enrollee() {
		super();
		activationStatus = false;
	}
	
	// NON-STANDARD METHODS
	
	/*!
		\brief Adds a Dependent to the associated Set, allocating the Set if it is null
		\param dependent The Dependent to add
		\return True if the Dependent was successfully added, false otherwise
		\sa Dependent
	*/
	public boolean addDependent(Dependent dependent) {
		if(dependents == null)
			dependents = new HashSet<Dependent>();
		return dependents.add(dependent);
	}
	
	/*!
		\brief Removes a Dependent from the associated Set via their id
		\param id The id of the Dependent to remove
		\return True if the Dependent was successfully removed, false otherwise
		\sa Dependent
	 */
	public boolean deleteDependentById(String id) {
		if(dependents == null)
			return false;
		return dependents.removeIf(dependent -> dependent.getId().equals(id));
	}
	
	// GETTERS AND SETTERS
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public boolean isActivationStatus() {
		return activationStatus;
	}
	public void setActivationStatus(boolean activationStatus) {
		this.activationStatus = activationStatus;
	}
	public Date getBirthDate() {
		return birthDate;
	}
	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}
	public String getPhoneNumber() {
		return phoneNumber;
	}
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}
	public Set<Dependent> getDependents() {
		return dependents;
	}
	public void setDependents(Set<Dependent> dependents) {
		this.dependents = dependents;
	}
}
